"""initial migration

Revision ID: 84d1fcbec39d
Revises: 
Create Date: 2025-05-15 19:50:49.354977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d1fcbec39d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_table')
    op.drop_table('chat_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_table',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_table_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['user_table.id'], name='chat_table_recipient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user_table.id'], name='chat_table_sender_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chat_table_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('message_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.id'], name='message_table_chat_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='message_table_pkey')
    )
    # ### end Alembic commands ###
